name: failure_handler
description: "Package Failure Handler"
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  firebase_database: ^12.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  supabase_flutter: ^2.9.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: